// <auto-generated />
namespace TunashaProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_of_namemm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_of_namemm));
        
        string IMigrationMetadata.Id
        {
            get { return "201604161308038_change_of_namemm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
